[package]
name = "zed_starlark"
version = "0.3.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[lib]
path = "src/starlark.rs"
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.0.6"

[build-dependencies]
toml_edit = "0.22.9"
